// Get all entities

GET http://localhost:8080/api/assignment/all
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiQ09PUkRJIiwic3ViIjoidGVzdHVzZXJAY29vcmRpLnRyYW5zbWkuY29tIiwiaWF0IjoxNzMxOTY0MTAwLCJleHAiOjE3MzIwMDAxMDB9.70bdbjuQNvviUOeNRHWiopkN_C3QpgFImsfliIuWWEpGNcv2HbYoavQdJTmpucd6

###
GET http://localhost:8080/api/bus/all
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiUEFTU0VOR0VSIiwic3ViIjoidGVzdHVzZXJAdHJhbnNtaS5jb20iLCJpYXQiOjE3MzE5NjQwMTYsImV4cCI6MTczMjAwMDAxNn0.mRUJ9CbIlTiZraCsOj4nYIwEL7b2snkO51DAqH7PEe1vuXSjkbwSl6x23GjOOsqK

###
GET http://localhost:8080/api/driver/all
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiQ09PUkRJIiwic3ViIjoidGVzdHVzZXJAY29vcmRpLnRyYW5zbWkuY29tIiwiaWF0IjoxNzMxOTgzNTI4LCJleHAiOjE3MzIwMTk1Mjh9.tyGk06ENq82agPSK1mhDRR_AA7-G9vQuKTQaPu54_7xHK5YIihsIycYPrGBMupLu

###
GET http://localhost:8080/api/route/all
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiJ0ZXN0dXNlckBhZG1pbi50cmFuc21pLmNvbSIsImlhdCI6MTczMTk2NDE0MCwiZXhwIjoxNzMyMDAwMTQwfQ.OdAiLQPeyIEKagunblMtLQQFQm-aBkZ_baNjubNdfnA-a5lCvYxh1fJW7DxlKlTQ

###
GET http://localhost:8080/api/schedule/all
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiJ0ZXN0dXNlckBhZG1pbi50cmFuc21pLmNvbSIsImlhdCI6MTczMTk2NDE0MCwiZXhwIjoxNzMyMDAwMTQwfQ.OdAiLQPeyIEKagunblMtLQQFQm-aBkZ_baNjubNdfnA-a5lCvYxh1fJW7DxlKlTQ

// Authentication

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "testuser@coordi.transmi.com",
    "password": "password123"
}

###

POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "email": "testuser@coordi.transmi.com",
    "password": "password123",
    "firstName": "user",
    "lastName": "test"
}

// Creating some entities

###
POST http://localhost:8080/api/assignment/create
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiQ09PUkRJIiwic3ViIjoidGVzdHVzZXJAY29vcmRpLnRyYW5zbWkuY29tIiwiaWF0IjoxNzMxOTY0MTAwLCJleHAiOjE3MzIwMDAxMDB9.70bdbjuQNvviUOeNRHWiopkN_C3QpgFImsfliIuWWEpGNcv2HbYoavQdJTmpucd6
Content-Type: application/json

{
  "idBus": 2,
  "idRoute": 2,
  "idDriver": 1,
  "idSchedule": 1
}

###
POST http://localhost:8080/api/bus/create
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiQ09PUkRJIiwic3ViIjoidGVzdHVzZXJAY29vcmRpLnRyYW5zbWkuY29tIiwiaWF0IjoxNzMxOTY0MTAwLCJleHAiOjE3MzIwMDAxMDB9.70bdbjuQNvviUOeNRHWiopkN_C3QpgFImsfliIuWWEpGNcv2HbYoavQdJTmpucd6
Content-Type: application/json

{
    "plate": "XYZ987",
    "model": "Volvo OZ"
}

### 
POST http://localhost:8080/api/route/create
Content-Type: application/json

{
  "code": "R001",
  "stations": [
    "Station A",
    "Station B",
    "Station C"
  ]
}

###

POST http://localhost:8080/api/schedule/create
Content-Type: application/json

{
  "days": [
    "Monday",
    "Tuesday",
    "Wednesday"
  ],
  "timeStart": "10:00",
  "timeEnd": "17:02"
}


// Reading some entities

###

GET http://localhost:8080/api/bus/read/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiUEFTU0VOR0VSIiwic3ViIjoidGVzdHVzZXJAZ21haWwuY29tIiwiaWF0IjoxNzMxOTYxNjg3LCJleHAiOjE3MzE5OTc2ODd9.shJ3l-fapcjpDjxDqaN6touJHT5T4qV6IHXMToTkaKfF9U-OpNpbWPqOyAYJnTa4


// Updating some entities

###
PUT http://localhost:8080/api/assignment/update/1
Content-Type: application/json

{
  "idBus": "2",
  "idRoute": "3"
}

###
PUT http://localhost:8080/api/bus/update/1
Content-Type: application/json

{
  "plate": "XYZ987",
  "model": "Mercedes 2017"
}

###
PUT http://localhost:8080/api/route/update/1
Content-Type: application/json

{
  "code": "R0001",
  "stations": ["Lunes", "Martes"]
}

// Deleting some entities

###
DELETE http://localhost:8080/api/assignment/delete/3

###
DELETE http://localhost:8080/api/bus/delete/1 

###
DELETE http://localhost:8080/api/driver/delete/1

###
DELETE http://localhost:8080/api/route/delete/20

###
DELETE http://localhost:8080/api/schedule/delete/2