// Get all entities

GET http://localhost:8080/api/assignment/all

###
GET http://localhost:8080/api/bus/all

###
GET http://localhost:8080/api/driver/all

###
GET http://localhost:8080/api/route/all

###
GET http://localhost:8080/api/schedule/all

// Creating some entities

###
POST http://localhost:8080/api/bus/create
Content-Type: application/json

{
    "plate": "XYZ987",
    "model": "Volvo OZ"
}

### 
POST http://localhost:8080/api/route/create
Content-Type: application/json

{
  "code": "R001",
  "stations": [
    "Station A",
    "Station B",
    "Station C"
  ]
}


// Updating some entities

###
PUT http://localhost:8080/api/bus/update/1
Content-Type: application/json

{
  "plate": "XYZ987",
  "model": "Mercedes 2017"
}

###
PUT http://localhost:8080/api/route/update/1
Content-Type: application/json

{
  "code": "R0001",
  "stations": ["Lunes", "Martes"]
}

// Deleting some entities

###
DELETE http://localhost:8080/api/assignment/delete/3

###
DELETE http://localhost:8080/api/bus/delete/20 

###
DELETE http://localhost:8080/api/driver/delete/20

###
DELETE http://localhost:8080/api/route/delete/20

###
DELETE http://localhost:8080/api/schedule/delete/2